# --- Basic options --- #

# Name of website
title: Wallisson Carvalho

# Short description of your site
description: Water Resources Researcher 

# Your name to show in the footer
author: Wallisson Moreira de Carvalho

# --- List of links in the navigation bar --- #

navbar-links:
  HydroBr: "HydroBr"
  Search:
    - Filter Tags: "tags"
    - Text Search: "search"
  My Projects: "projects"
  About Me/Contact: "about"


# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/me.jpg"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer options --- #
# Select the social network links that you want to show in the footer.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "cmwallisson@gmail.com"
  github: wallissoncarvalho
  twitter: cmwallisson
  rss: true
  linkedin: wallissoncarvalho
#  instagram: wallissoncarvalho
#  telephone: +5582999999999

# --- General options --- #
# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "wallissoncarvalho.github.io"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-168655832-1"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "wallissongithubio"
# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"



# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Maceio"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
